# Use python3.6-nodejs10 image
FROM nikolaik/python-nodejs:python3.6-nodejs10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Bundle app source
COPY . .

CMD [ "node", "ml-server.js" ]
